name: Pester tests
on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Pester test
      shell: pwsh
      run: |
        Install-Module Pester -Force
        Invoke-Pester -Output Diagnostic -Path test -PassThru |Export-NUnitReport -Path TestResults.xml
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
        nunit_files: "TestResults.xml"
