name: Pester tests
on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Pester test
      shell: pwsh
      run: |
        Install-Module Pester -Force
        Invoke-Pester -Output Diagnostic -Path test
