name: Pester tests
on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Pester test
      shell: pwsh
      run: |
        Install-Module Pester
        Invoke-Pester -Output Diagnostic -Path test
