name: Pester tests
on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Pester test
      shell: pwsh
      run: |
        Install-Module Pester -Force
        Get-ChildItem -Dir -Rec
        Invoke-Pester -Output Diagnostic -Path test
